name = "chatwoot-proxy-galle"
main = "chatwoot-proxy.js"
compatibility_date = "2024-11-01"

[vars]
# Comma-separated list of allowed origins
ALLOWED_ORIGINS = "https://dashboard.galle18k.com,http://localhost:8081,https://galleorolaminado18k.github.io"

# Set these with `wrangler secret put` in your Cloudflare account (not stored in repo)
# CHATWOOT_URL = "https://app.chatwoot.com"
# CHATWOOT_API_TOKEN = "<your_api_access_token>"
# CHATWOOT_ACCOUNT_ID = "429699"

