// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_SUPABASE_ANON_KEY;

// Valores por defecto si no están configuradas las variables
const DEFAULT_URL = "https://placeholder.supabase.co";
const DEFAULT_KEY = "placeholder-anon-key";

const finalUrl = SUPABASE_URL || DEFAULT_URL;
const finalKey = SUPABASE_ANON_KEY || DEFAULT_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn("[Supabase] Usando valores por defecto. Configura VITE_SUPABASE_URL y VITE_SUPABASE_ANON_KEY para funcionalidad completa.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(finalUrl, finalKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
