name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Asegúrate de que esta versión sea compatible con tu proyecto
          cache: 'npm' # Habilitar caché para npm

      - name: Display Node.js and npm versions and PATH
        run: |
          node -v
          npm -v
          echo $PATH

      - name: Install dependencies
        run: npm install

      - name: Audit and fix npm vulnerabilities
        run: npm audit fix || true # '|| true' para que no falle si hay vulnerabilidades no corregibles

      - name: List node_modules content (for debugging)
        run: ls -la node_modules

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: dashboard.galle18k.com # Opcional: si tienes un dominio personalizado
