name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Añadir permisos de escritura para el bot de GitHub Actions
    env:
      VITE_SUPABASE_URL: https://evjgujiyjplvbudgfiwr.supabase.co
      VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2amd1aml5anBsdmJ1ZGdmaXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTc4NzIsImV4cCI6MjA3NTY3Mzg3Mn0.EnJIuzxjw6tpURxclEZ60ySDqKkz6vltjSQPEWHtYzI
      # Chatwoot
      VITE_CHATWOOT_ENABLED: true
      VITE_CHATWOOT_URL: https://app.chatwoot.com
      VITE_CHATWOOT_WEBSITE_TOKEN: c5S9SqxkumtX7GAZdc9LQnri
      VITE_BRIDGE_API_URL: https://chatwoot-proxy-galle.galleorolaminado18k.workers.dev
      VITE_CHATWOOT_ACCOUNT_ID: 138167
      # Meta Ads API - Multi-token configuration
      VITE_META_BUSINESS_ID: 1067806144007153
      # Token principal (cuenta 5518735214914409 - GALLE 18K DETAL)
      VITE_META_ACCESS_TOKEN: EAAC4zHE6iMYBPt67m4GY5ML3mWCGeBPiO6N6i6i751ZCOfdSSytbfrXnQ6mRcZBHhJXZBmZCWmgZB4V9Ws4oBpQTTMO6zequoZBNBRuXgHGggZCMNWAaMB3L2ubFyBieDeMj5WLP01AZB04Q7vC0DOs1SGkUUszktaBiXcVKapvGwXwotsTyy0MHZA1I52fZB4Rv4DVQZDZD
      # Token secundario (cuenta 360084149294973 - orolaminado18kcucuta)
      VITE_META_ACCESS_TOKEN_2: EAAC4zHE6iMYBPsv42MRv12UQy7jwavaEVw0DNYWKPFUkio21pBs7rzaRSjN7MzafBZAlyyYbRorAd1scPUg6gsyUpZBuT2SaAWvWA8IbNM7E2fTvlFEy8hcFsCzDajYUJLZAGlZArXKvoAwzzTTj3sx6HqNmX6ZANTRTIFYhc7s70AYVyqYFjzUzE0FBhxZAfyZBAZDZD
      VITE_META_AD_ACCOUNT_IDS: 360084149294973,5518735214914409
      VITE_META_AD_ACCOUNT_NAMES: orolaminado18kcucuta,GALLE 18K DETAL
      VITE_META_AD_ACCOUNT_ID: 360084149294973
      VITE_META_AD_ACCOUNT_NAME: orolaminado18kcucuta
      # Fallback Auth
      VITE_FALLBACK_AUTH_EMAIL: demo@dashboard.galle18k.com
      VITE_ENABLE_FALLBACK_AUTH: true
      VITE_FALLBACK_ALLOWED_EMAILS: demo@dashboard.galle18k.com,galleorolaminado18k@gmail.com

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Asegúrate de que esta versión sea compatible con tu proyecto
          cache: 'npm' # Habilitar caché para npm

      - name: Display Node.js and npm versions and PATH
        run: |
          node -v
          npm -v
          echo $PATH

      - name: Install dependencies
        run: npm ci

      - name: List node_modules content (for debugging)
        run: ls -la node_modules

      - name: List node_modules/.bin content (for debugging)
        run: ls -la node_modules/.bin

      - name: Debug React and Rollup paths
        run: |
          echo "--- Listing node_modules/react ---"
          ls -la node_modules/react
          echo "--- Listing node_modules/react-dom ---"
          ls -la node_modules/react-dom
          echo "--- Content of node_modules/rollup/dist/es/shared/parseAsset.js ---"
          cat node_modules/rollup/dist/es/shared/parseAsset.js || echo "File not found or cannot be read."

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: dashboard.galle18k.com # Opcional: si tienes un dominio personalizado
